name: tests unitaires
on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Afficher nom de la branche et OS
        run: |
          echo "Nom branche: ${{ github.ref }}"
          echo "OS runner: ${{ runner.os }}"

      - name: Set up Python for Demo
        uses: actions/setup-python@v4

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest TP1/test.py

